defaults:
  - model: tdanet_ffnonly
  - metrics: fast_metrics
  - datasets: dataset_eval # we do not want to run inference on training data
  - dataloader: dataloader
  - transforms: transforms_supervised_mix
  - _self_

data_root: "."
dataset_url: null

inferencer:
  device_tensors: ["audio_mix"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: null # any name here, can be a dataset name
  seed: 1
  from_pretrained: null # path to the pretrained model
