train:
  _target_: torch.utils.data.DataLoader
  batch_size: 10
  pin_memory: True
  persistent_workers: False

inference:
  _target_: torch.utils.data.DataLoader
  batch_size: 10
  pin_memory: True
  persistent_workers: False
